### ISSUE TITLE
Deprecated selector in `ninja-ui-syntax/index.less`

### ISSUE THREAD

**Issue by cesasol** [licatajustin/ninja-ui-syntax#1]
In `ninja-ui-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by licatajustin** [comment]
Thanks @cesasol. I'll look into these and update accordingly.

**Comment by licatajustin** [comment]
This has been resolved in the latest version, v0.1.4.

Thanks @cesasol 🎉
